./server --id 1 &
./server --id 2 &
./server --id 3 &
./server --id 4 &
./server --id 5 &
./server --id 6 &
./server --id 7 &
./server --id 8 &
./server --id 9 &
./server --id 10 &
./server --id 11 &
./server --id 12 &
./server --id 13 &
./server --id 14 &
./server --id 15 &
./server --id 16 &
./server --id 17 &
./server --id 18 &
./server --id 19 &
./server --id 20 &
./server --id 21 &
./server --id 22 &
./server --id 23 &
./server --id 24 &
./server --id 25 &
./server --id 26 &
./server --id 27 &
./server --id 28 &
./server --id 29 &
./server --id 30 &
./server --id 31 &
./server --id 32 &
./server --id 33 &
./server --id 34 &
./server --id 35 &
./server --id 36 &
./server --id 37 &
./server --id 38 &
./server --id 39 &
./server --id 40 &
./server --id 41 &
./server --id 42 &
./server --id 43 &
./server --id 44 &
./server --id 45 &
./server --id 46 &
./server --id 47 &
./server --id 48 &
./server --id 49 &
./server --id 50 &
sleep 20
./load_balancer &